FROM python:3.6-slim
COPY ./app-fall.py /deploy/
COPY ./requirements.txt /deploy/

COPY ./final_fall_detection_model.sav /deploy/
WORKDIR /deploy/
RUN python -m pip install --upgrade pip 
RUN pip install -r requirements.txt
EXPOSE 80
ENTRYPOINT ["python", "app-fall.py"]
